name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Rust CI
        uses: ./.github/actions/rust-ci

  nix:
    name: Nix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Nix CI
        uses: ./.github/actions/nix-ci
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
